== Guava caches

Guava caches can be instrumented with the registry. Because it is not possible to turn on metrics after the cache is constructed, you must call `recordStats()` on the `CacheBuilder`.

```java
@Repository
class PersonRepository {
    LoadingCache<String, Person> personBySsn;

    public PersonRepository(MeterRegistry registry) {
        personBySsn = GuavaCacheMetrics.monitor(registry, CacheBuilder.newBuilder().recordStats().build(),
            "people.cache", // base metric name
            "lookup.key", "ssn" // <- any number of tag key/value pairs
        );
    }
}
```

Cache instrumentation results in several gauges whose names are
prefixed by the provided name (`people.cache` in this example),
corresponding to the stats recorded in `CacheStats`.

The original cache instance is _unchanged_ by instrumentation.

== Caffeine caches

Caffeine caches can be instrumented with the registry. Because it is not possible to turn on metrics after the cache is constructed, you must call `recordStats()` on the `Caffeine` builder.

```java
@Repository
class PersonRepository {
    Cache<String, Person> personBySsn;

    public PersonRepository(MeterRegistry registry) {
        personBySsn = CaffeineCacheMetrics.monitor(registry, Caffeine.newBuilder().recordStats().build(),
            "people.cache", // base metric name
            "lookup.key", "ssn" // <- any number of tag key/value pairs
        );
    }
}
```

Cache instrumentation results in several gauges whose names are
prefixed by the provided name (`people.cache` in this example),
corresponding to the stats recorded in `CacheStats`.

The original cache instance is _unchanged_ by instrumentation.
