A gauge is a handle to get the current value. Typical examples for gauges
would be the size of a collection or map or number of threads in a running state.

TIP: Gauges are useful for monitoring things with natural upper bounds. We don't recommend
using a gauge to monitor things like request count, as they can grow without bound for
the duration of an application instance's life.

Micrometer takes the stance that gauges should be sampled and not set, so
there is no information about what might have occurred between samples. After all,
any intermediate values set on a gauge are lost by the time the gauge value is reported
to a metrics backend anyway, so there seems to be little value in setting those intermediate
values in the first place.

If it helps, think of a `Gauge` as a heisengauge - a meter that only changes when it
is observed.

The `MeterRegistry` interface contains a number of convenience methods for instrumenting
collections, maps, executors, and caches with gauges.

[source, java]
----
AtomicInteger n = registry.gauge("numberGauge", new AtomicInteger(0)); <1>
List<String> list = registry.gauge("listGauge", Collections.emptyList(), new ArrayList<>(), List::size); <2>
List<String> list = registry.collectionSize(new ArrayList<>(), "listGauge2"); <3>
Map<String, Integer> map = registry.mapSize(new HashMap<>(), "mapGauge");
----
<1> The simplest form of gauge monitors any `Number` instance. Note that unlike other meter types
you don't get a reference to the `Gauge` when creating one, but rather the thing being observed.
This is because of the heisenguage principal; the gauge is self sufficient once created, so you should
never need to interact with it. This allows us to just give you back the instrumented object, which
allows for quick one liners that both create the object to be observed and set up metrics around it.
<2> A slightly more common form of gauge is one that monitors some non-numeric object. The last argument
establishes the function that is used to determine the value of the gauge when the gauge is observed.
<3> A more convenient form of (2) for when you simply want to monitor collection size.

All of the different forms of creating a gauge maintain only a weak reference to the object being observed, so
as not to prevent garbage collection of the object.

ifeval::["{system}" == "prometheus"]
NOTE: In Prometheus, a gauge is a generalization of a counter that also happens to allow
for decrementing. If you view a gauge as something that is actively set by the application
application code rather than sampled, it is clear that your code would have to increment
and decrement the gauge as the size of the thing being measured changes. Diligent incrementing
and decrementing throughout the application code yields the same result as the heisengauge,
ultimately.
endif::[]