Timers and distribution summaries can be enriched with histogram statistics that yield a counter time series for each of a set of buckets.

Histograms can be used to compute quantiles or other summary statistics in some monitoring backends. Because histograms buckets are exposed as individual counters to the monitoring backend, it is possible to aggregate observations across a distributed system and compute summary statistics like quantiles for an entire cluster.

Naturally, the error rate of the computed summary statistic will be higher because of the lossy nature of putting data in buckets.

Micrometer supports both cumulative and non-cumulative (normal) histograms along with specialized timers for computed aggregable percentiles and performing implementation independen time scaling. The following code shows the creation of a historgram.

```java
DistributionSummary hist = DistributionSummary.builder("summary")
        .histogram(Histogram.linear(0, 10, 20))
        .register(registry);
```

With this construction, the registry is allowed to pick whether the histogram is normal or cumulative, depending on what is canonical for that system. This sample constructs a cumulative histogram consisting of 20 buckets, one every 10 units beginning at 0.

== Time Scaled Histograms

Bucket functions are available that are designed to sample time an implementation-neutral way. Specifically, bucket tag keys are scaled to the base unit of time of your registry implementation, and inbound observations are scaled from registry base time to the bucket functions' time unit to bucket the value. For example:

```java
Timer timer = Timer.builder("timer")
        .histogram(Histogram.linearTime(TimeUnit.MILLISECONDS, 0, 10, 20))
        .register(registry);
```

If the base unit of time for a registry is seconds, the bucket tag keys reported to that registry will be 0.00, 0.01, 0.02, etc.

== Percentile Approximations

`Histogram.percentiles()` and `Histogram.percentilesTimer()` choose a set of buckets for you that have been empirically determined to have a less than 10% error bound (and often tighter) for most distribution summaries and timers, respectively. This allows you to build aggregable percentile approximations without requiring _a priori_ knowledge of the range of values that
your meter might observe.