= Micrometer Reference Manual
Jon Schneider <jschneider@pivotal.io>
:toc:
:sectnums:
:dimensional: true

ifeval::["{system}" == "jmx"]
:dimensional: false
endif::[]
ifeval::["{system}" == "graphite"]
:dimensional: false
endif::[]
ifeval::["{system}" == "ganglia"]
:dimensional: false
endif::[]

== Install

include::install.adoc[leveloffset=+1]

== Meter registry

include::registry.adoc[leveloffset=+1]

== Meters

Micrometer packs with a supported set of `Meter` primitives including:
`Timer`, `Counter`, `Gauge`, `DistributionSummary`, and `LongTaskTimer`. Note that different meter types
result in a different number of metrics. For example, while there is a single metric that represents a
`Gauge`, a `Timer` measures both number of timed events and the total time of all events timed.

A meter is uniquely identified by its name and dimensions.

=== Dimensions/Tags

include::tags.adoc[leveloffset=+2]

=== Counters

include::counters.adoc[leveloffset=+2]

=== Timers

include::timers.adoc[leveloffset=+2]

=== Long task timers

include::long-task-timers.adoc[leveloffset=+2]

=== Gauges

include::gauges.adoc[leveloffset=+2]

=== Distribution summaries

include::distribution-summaries.adoc[leveloffset=+2]

ifeval::["{dimensional}" == "true"]

== Summary statistics

Micrometer provides quantile statistics computed at instrumentation time and histograms for use
in calculating quantile statistics at query time for monitoring systems that support this.

=== Quantiles

include::quantiles.adoc[leveloffset=+2]

=== Histograms

include::histograms.adoc[leveloffset=+2]

endif::[]

== Binders

Meter binders define collections of meters to add to a registry. Binders are used to
encapsulate the best practices for monitoring a certain types of objects or a part
of the application's environment. Micrometer ships with a basic set of binders.

=== JVM and system monitoring

include::jvm.adoc[leveloffset=+2]

=== Cache monitoring

include::caches.adoc[leveloffset=+2]

=== `Executor` and `ExecutorService` monitoring

include::executors.adoc[leveloffset=+2]

=== Logback monitoring

include::logback.adoc[leveloffset=+2]

== Spring integration

As of Spring Boot 2.0 / Spring Framework 5.0, Micrometer is the instrumentation library powering the delivery of application metrics from Spring.
The `micrometer-spring-legacy` module provides drop-down support for Spring Boot 1.x / Spring Framework 4.x.

In Gradle:

[source,groovy,subs=+attributes]
----
compile 'io.micrometer:micrometer-spring-legacy:latest.release'
----

Or in Maven:

[source,xml,subs=+attributes]
----
<dependency>
  <groupId>io.micrometer</groupId>
  <artifactId>micrometer-spring-legacy-starter</artifactId>
  <version>${micrometer.version}</version>
</dependency>
----

=== Configuring

include::spring-configuring.adoc[leveloffset=+2]

=== Web monitoring

include::spring-web.adoc[leveloffset=+2]

=== Scheduling

include::spring-scheduling.adoc[leveloffset=+2]

=== Data source monitoring

include::spring-datasource.adoc[leveloffset=+2]