A meter is uniquely identified by its name and dimensions. We use the term dimensions and tags interchangeably, and the Micrometer interface is `Tag` simply because it is shorter. As a general rule it should be possible to use the name as a pivot. Dimensions allow a particular named metric to be sliced to drill down and reason about the data. This means that if just the name is selected, the user can drill down using other dimensions and be able to reason about the value being shown.

== Naming metrics

Micrometer employs a naming convention that separates words with '.'. Because different monitoring systems have different recommendations regarding naming convention, and some naming conventions may actually be breaking for one system and not another, each Micrometer implementation for a monitor system packs with a naming convention that transforms dot notation names to the recommended naming convention. Additionally, this naming convention implementation sanitizes names and tags of special characters that are disallowed by the monitoring system they are designed for. You can override the default naming convention for a registry if you'd like by implementing `NamingConvention` and setting it on the registry with:

[source,java]
----
registry.config().namingConvention(myCustomNamingConvention);
----

With naming conventions in place, the following timer registered in Micrometer looks good natively in a wide variety of monitoring systems:

[source,java]
----
registry.timer("http.server.requests");
----

1. Prometheus - `http_server_requests_duration_seconds`
2. Atlas - `httpServerRequests`
3. Graphite - `http.server.requests`
4. InfluxDB - `http_server_requests`

By adhering to Micrometer's dot notation convention, you guarantee the maximum degree of portability for your metric names across monitoring systems.

== Tag naming

Suppose we are trying to measure the number of threads in a thread pool and the number of rows in a database table.

*Recommended approach*

[source,java]
----
registry.counter("threadpool.size", "id", "server.requests")
registry.counter("db.size", "table", "users")
----

This variant provides enough context so that if just the name is selected the value can be reasoned about and is at least potentially meaningful. For example if we select `threadpool.size` we can see the total number of threads in all pools. Then we can group by or select an `id` to drill down further or perform comparative analysis on the contribution of each functional area to the number of threads consumed by the instrumented app.

*Bad approach*

[source,java]
----
registry.counter("size",
    "class", "ThreadPool",
    "id", "server.requests");

registry.counter("size",
    "class", "Database",
    "table", "users");
----

In this approach, if we select `size` we will get a value that is an aggregate of the number of threads and the number of items in a database. This time series is not useful without further dimensional drill-down.

== Common tags

Common tags can be defined at the registry level and are added to every metric reported to the monitoring system.
This is generally used for dimensional drill-down on the operating environment, like host, instance, region, stack, etc.

[source,java]
----
registry.config().commonTags("stack", "prod", "region", "us-east-1");
registry.config().commonTags(Arrays.asList(Tag.of("stack", "prod"), Tag.of("region", "us-east-1"))); // equivalently
----

Calls to `commonTags` append additional common tags.

IMPORTANT: If you are in the Spring environment, add common tags by adding a `MetricRegistryConfigurer` bean to be sure that common tags are applied before autoconfigured meter binders.