== Automated Documentation Generation

By using the https://github.com/micrometer-metrics/micrometer-docs-generator[Micrometer Docs Generator] project and by implementing the `ObservationDocumentation`, `SpanDocumentation` or `MeterDocumentation` interfaces as an `enum`, you can scan your sources and generate Asciidoctor documentation. This lets you maintain the docuemntation for your observability instrumentation in code, and as long as you use the `enum` implementation in your instrumentation, it ensures that your documentation stays in-sync with the instrumentation.

The following example shows a Maven `pom.xml` with the Micrometer Docs Generator project:

.pom.xml
[source,xml,subs=+attributes]
-----
include::../../../samples/src/test/resources/docs-generator-pom.xml[indent=0]
-----

The following example shows a Gradle `build.gradle` with the Micrometer Docs Generator project:

.build.gradle
[source,groovy,subs=+attributes]
-----
include::../../../samples/src/test/resources/docs-generator-build.gradle[indent=0,tag=main]
-----

Running these tasks would lead to generation of adoc files similar to these :

._metrics.adoc
[source,adoc,subs=+attributes]
-----
[[observability-metrics]]
=== Observability - Metrics

Below you can find a list of all samples declared by this project.

[[observability-metrics-task-runner-observation]]
==== Task Runner Observation

> Observation created when a task runner is executed.

**Metric name** `spring.cloud.task.runner` (defined by convention class `org.springframework.cloud.task.configuration.observation.DefaultTaskObservationConvention`). **Type** `timer` and **base unit** `seconds`.

Fully qualified name of the enclosing class `org.springframework.cloud.task.configuration.observation.TaskDocumentedObservation`.

IMPORTANT: All tags must be prefixed with `spring.cloud.task` prefix!

.Low cardinality Keys
|===
|Name | Description
|`spring.cloud.task.runner.bean-name`|Name of the bean that was executed by Spring Cloud Task.
|===
-----

._spans.adoc
[source,adoc,subs=+attributes]
-----
[[observability-spans]]
=== Observability - Spans

Below you can find a list of all spans declared by this project.

[[observability-spans-task-runner-observation]]
==== Task Runner Observation Span

> Observation created when a task runner is executed.

**Span name** `spring.cloud.task.runner` (defined by convention class `org.springframework.cloud.task.configuration.observation.DefaultTaskObservationConvention`).

Fully qualified name of the enclosing class `org.springframework.cloud.task.configuration.observation.TaskDocumentedObservation`.

IMPORTANT: All tags and event names must be prefixed with `spring.cloud.task` prefix!

.Tag Keys
|===
|Name | Description
|`spring.cloud.task.runner.bean-name`|Name of the bean that was executed by Spring Cloud Task.
|===
-----

=== Options

The main entry class for the docs generation is the `DocsGeneratorCommand` class.
This class takes the following options:

.Optional parameters
[cols="1,1"]
|===
| `--metrics`
| Generate metrics documentation.

| `--spans`
| Generate spans documentation.

| `--conventions`
| Generate observation conventions documentation.

| `--metrics-template=<location>`
| Handlebars template file location. This can be a path in the classpath or file system,  +
such as  `templates/metrics.adoc.hbs` or `/home/example/bar.hbs`

| `--spans-template=<location>`
| Handlebars template file location. This can be a path in the classpath or file system,  +
such as  `templates/spans.adoc.hbs` or `/home/example/bar.hbs`

| `--conventions-template=<location>`
| Handlebars template file location. This can be a path in the classpath or file system,  +
such as  `templates/conventions.adoc.hbs` or `/home/example/bar.hbs`

| `--metrics-output=<location>`
| Generated metrics doc file location. This can be an absolute path or a path relative to the output directory.  +
Default: `_metrics.adoc`

| `--spans-output=<location>`
| Generated spans doc file location. This can be an absolute path or a path relative to the output directory.  +
Default: `_spans.adoc`

| `--conventions-output=<location>`
| Generated observation convention doc file location. This can be an absolute path or a path relative to the output directory.  +
Default: `_conventions.adoc`
|===
