= Tracing support
:toc:
:sectnums:
:dimensional: true

== Purpose

A library that assists with context propagation across different types of context
mechanisms such as `ThreadLocal`, Reactor https://projectreactor.io/docs/core/release/reference/#context[Context]
and others.

Abstractions:

* `ThreadLocalAccessor` - contract to assist with access to a `ThreadLocal` value.
* `ContextAccessor` - contract to assist with access to a `Map`-like context.
* `ContextRegistry` - registry for instances of `ThreadLocalAccessor` and `ContextAccessor`.
* `ContextSnapshot` - holder of contextual values, that provides methods to capture and to propagate.

Example Scenarios:

* In imperative code, e.g. Spring MVC controller, capture `ThreadLocal` values into a
`ContextSnapshot`. After that use the snapshot to populate a Reactor `Context` with the
captured values, or to wrap a task (e.g. `Runnable`, `Callable`, etc) or an `Executor`
with a decorator that restores `ThreadLocal` values when the task executes.
* In reactive code, e.g. Spring WebFlux controller, create a `ContextSnapshot` from
Reactor `Context` values. After that use the snapshot to restore `ThreadLocal` values
within a specific stage (operator) of the reactive chain.

Context values can originate from any context mechanism and propagate to any other, any
number of times. For example, a value in a `Reactor` context may originate as a
`ThreadLocal`, and may yet become a `ThreadLocal` again, and so on.

Generally, imperative code should interact with `ThreadLocal` values as usual, and
likewise Reactor code should interact with the Reactor `Context` as usual. The Context
Propagation library is not intended to replace those, but to assist with propagation when
crossing from one type of context to another, e.g. when imperative code invokes a Reactor
chain, or when a Reactor chain invokes an imperative component that expects
`ThreadLocal` values.

The library is not limited to context propagation from imperative to reactive. It can
assist in asynchronous scenarios to propagate `ThreadLocal` values from one thread to
another. It can also propagate to any other type of context for which there is a
registered `ContextAccesor` instance.

== Installing

Snapshots are published to `repo.spring.io` for every successful build on the `main` branch and maintenance branches.

Milestone releases are published to https://repo.spring.io/milestone. Include that as a maven repository in your build
configuration to use milestone releases. Note that milestone releases are for testing purposes and are not intended for
production use.

The following example shows the required dependency in Gradle:

[source,groovy,subs=+attributes]
----
implementation 'io.micrometer:context-propagation:latest.integration'
----

The following example shows the required dependency in Maven:

[source,xml,subs=+attributes]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>context-propagation</artifactId>
            <version>${micrometer-context-propagation.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    <dependency>
        <groupId>io.micrometer</groupId>
        <artifactId>context-propagation</artifactId>
        <version>${micrometer-context-propagation.version}</version>
    </dependency>
</dependencies>
----

== Usage Examples

include::context-usage.adoc[leveloffset=+1]
