= Micrometer Datadog
Jon Schneider <jschneider@pivotal.io>
:toc:
:sectnums:
:system: datadog

Datadog is a dimensional time-series SaaS with built-in dashboarding and alerting.

== Installation and Configuration

Micrometer supports shipping metrics to Datadog directly via its HTTP API or through DogStatsD via the link:/docs/registry/statsD[StatsD registry].
The API approach is far more efficient if you need to choose between the two.

=== Direct to Datadog API approach

In Gradle:

[source,groovy]
----
compile 'io.micrometer:micrometer-registry-datadog:latest.release'
----

Or in Maven:

[source,xml]
----
<dependency>
  <groupId>io.micrometer</groupId>
  <artifactId>micrometer-registry-datadog</artifactId>
  <version>${micrometer.version}</version>
</dependency>
----

Metrics are rate-aggregated and pushed to datadoghq on a periodic interval. Rate aggregation performed by the registry yields datasets that are quite similar to those produced by dogstatsd.

[source, java]
----
DatadogConfig config = new DatadogConfig() {
    @Override
    public Duration step() {
        return Duration.ofSeconds(10);
    }

    @Override
    public String get(String k) {
        return null; // accept the rest of the defaults
    }
};
MeterRegistry registry = new DatadogMeterRegistry(config, Clock.SYSTEM);
----

`DatadogConfig` is an interface with a set of default methods. If, in the implementation of `get(String k)`, rather than returning `null`, you instead bind it to a property source, you can override the default configuration through properties. For example, Micrometer's Spring Boot support binds properties prefixed with `management.metrics.export.datadog` directly to the `DatadogConfig`:

[source, yaml]
----
management.metrics.export.datadog:
    apiKey: YOURKEY

    # You will probably want disable Datadog publishing in a local development profile.
    enabled: true

    # The interval at which metrics are sent to Datadog. The default is 1 minute.
    step: 1m
----

`DatadogConfig.hostTag()` specifies a tag key that will be mapped to https://docs.datadoghq.com/api/v1/metrics/#submit-metrics[the `host` field] when shipping metrics to Datadog.
For example, if `DatadogConfig.hostTag()` returns "host", the tag having "host" as its key will be used.
You can set the tag via common tags as follows:

```java
registry.config().commonTags("host", "my-host");
```

=== Through DogStatsD approach

In Gradle:

[source,groovy,subs=+attributes]
----
compile 'io.micrometer:micrometer-registry-statsd:latest.release'
----

Or in Maven:

[source,xml,subs=+attributes]
----
<dependency>
  <groupId>io.micrometer</groupId>
  <artifactId>micrometer-registry-statsd</artifactId>
  <version>${micrometer.version}</version>
</dependency>
----

Metrics are shipped immediately over UDP to DogStatsD using Datadog's flavor of the StatsD line protocol. `java-dogstatsd-client` is _not_ needed on the classpath for this to work as Micrometer uses its own implementation.

[source,java]
----
StatsdConfig config = new StatsdConfig() {
    @Override
    public String get(String k) {
        return null;
    }

    @Override
    public StatsdFlavor flavor() {
        return StatsdFlavor.DATADOG;
    }
};

MeterRegistry registry = new StatsdMeterRegistry(config, Clock.SYSTEM);
----

Micrometer since 1.7.0 supports DogStatsD's https://docs.datadoghq.com/developers/dogstatsd/?tab=kubernetes#origin-detection-over-udp[origin detection over UDP] feature on Kubernetes if the `DD_ENTITY_ID` environment variable is properly set.
