= Micrometer Datadog
Jon Schneider <jschneider@pivotal.io>
:toc:
:sectnums:
:system: datadog

Datadog is a dimensional time-series SaaS with built-in dashboarding and alerting.

== Installation and Configuration

Micrometer supports shipping metrics to Datadog directly via its API or through Dogstatsd via the StatsD registry.
The API approach is far more efficient if you need to choose between the two.

=== Direct to Datadog API approach

In Gradle:

[source,groovy]
----
compile 'io.micrometer:micrometer-registry-datadog:latest.release'
----

Or in Maven:

[source,xml]
----
<dependency>
  <groupId>io.micrometer</groupId>
  <artifactId>micrometer-registry-datadog</artifactId>
  <version>${micrometer.version}</version>
</dependency>
----

Metrics are rate-aggregated and pushed to datadoghq on a periodic interval. Rate aggregation performed by the registry yields datasets that are quite similar to those produced by dogstatsd.

[source, java]
----
DatadogConfig config = new DatadogConfig() {
    @Override
    public Duration step() {
        return Duration.ofSeconds(10);
    }

    @Override
    public String get(String k) {
        return null; // accept the rest of the defaults
    }
};
MeterRegistry registry = new DatadogMeterRegistry(config, Clock.SYSTEM);
----

`DatadogConfig` is an interface with a set of default methods. If, in the implementation of `get(String k)`, rather than returning `null`, you instead bind it to a property source, you can override the default configuration through properties. For example, Micrometer's Spring Boot support binds properties prefixed with `management.metrics.export.datadog` directly to the `DatadogConfig`:

[source, yaml]
----
management.metrics.export.datadog:
    apiKey: YOURKEY

    # You will probably want disable Datadog publishing in a local development profile.
    enabled: true

    # The interval at which metrics are sent to Datadog. The default is 1 minute.
    step: 1m
----

=== Through Dogstatsd approach

In Gradle:

[source,groovy,subs=+attributes]
----
compile 'io.micrometer:micrometer-registry-statsd:latest.release'
----

Or in Maven:

[source,xml,subs=+attributes]
----
<dependency>
  <groupId>io.micrometer</groupId>
  <artifactId>micrometer-registry-statsd</artifactId>
  <version>${micrometer.version}</version>
</dependency>
----

Metrics are shipped immediately over UDP to Dogstatsd using Datadog's flavor of the StatsD line protocol. `java-dogstatsd-client` is _not_ needed on the classpath for this to work. Micrometer uses an alternative, non-blocking UDP implementation.

[source,java]
----
StatsdConfig config = new StatsdConfig() {
    @Override
    public String get(String k) {
        return null;
    }

    @Override
    public StatsdFlavor flavor() {
        return StatsdFlavor.DATADOG;
    }
};

MeterRegistry registry = new StatsdMeterRegistry(config, Clock.SYSTEM);
----
