= Micrometer Dynatrace
:toc:
:sectnums:
:system: dynatrace

https://www.dynatrace.com/[*Dynatrace*] is a Software Intelligence Platform featuring application performance monitoring (APM), artificial intelligence for operations (AIOps), IT infrastructure monitoring, digital experience management (DEM), and digital business analytics capabilities.
It can ingest multi-purpose dimensional time-series data and has built-in dashboarding. Both SaaS and self-hosted (Managed) deployments are offered.

include::install.adoc[]

== Configuring

For setting up new integrations with Dynatrace, it is recommended to use the latest version of the https://www.dynatrace.com/support/help/dynatrace-api/environment-api/metric-v2/[Dynatrace Metrics API] (`api-version: v2`).
More details on how to use the v2 API are provided further <<bookmark-apiv2, below>>.


=== Using a Dynatrace OneAgent installed on the host (preferred) [[bookmark-oneagent-example]]

If a Dynatrace OneAgent is installed on the host running Micrometer, metrics can be exported directly using the OneAgent without having to specify an endpoint URI or API token.
Use the following code in your project to export Micrometer metrics to the https://www.dynatrace.com/support/help/how-to-use-dynatrace/metrics/metric-ingestion/ingestion-methods/local-api/[local OneAgent endpoint]:

[source,java]
----
DynatraceConfig dynatraceConfig = new DynatraceConfig() {
    @Override
    public DynatraceApiVersion apiVersion() {
        return DynatraceApiVersion.V2;
    }

    @Override
    @Nullable
    public String get(String k) {
        // This method for retrieving arbitrary config items introduced by the interface is currently not used in DynatraceConfig.
        return null;
    }
};
MeterRegistry registry = new DynatraceMeterRegistry(dynatraceConfig, Clock.SYSTEM);
----

If you are working with Spring Boot, you can instead put the following properties in your `application-dynatrace.yml` in the `resources` folder.

[source,yml]
----
management.metrics.export.dynatrace:
    enabled: true
    api-version: v2
----

=== Using a custom endpoint

If no Dynatrace OneAgent is available, both the Dynatrace Metrics API v2 endpoint and an API token have to be specified.
The https://www.dynatrace.com/support/help/dynatrace-api/basics/dynatrace-api-authentication/[Dynatrace API token documentation] contains more information on how to create an API token.
The 'Ingest metrics' (`metrics.ingest`) permission is required on the token in order to ingest metrics.
It is recommended to limit scope to only this permission.

[source,java]
----
DynatraceConfig dynatraceConfig = new DynatraceConfig() {
    @Override
    public DynatraceApiVersion apiVersion() {
        return DynatraceApiVersion.V2;
    }

    @Override
    public String uri() {
        // The endpoint of the Dynatrace Metrics API v2 including path, e. g.
        // "https://{your-environment-id}.live.dynatrace.com/api/v2/metrics/ingest".
        // To be read from environment variables or a config file.
        return MY_DYNATRACE_URI;
    }

    @Override
    public String apiToken() {
        // Read from the environment or a config file.
        // It is *not* recommended to place secrets in config files
        // but rather to read them from env vars, for example.
        return MY_TOKEN;
    }

    @Override
    @Nullable
    public String get(String k) {
        // This method for retrieving arbitrary config items introduced by the interface is currently not used in DynatraceConfig.
        return null;
    }
};
MeterRegistry registry = new DynatraceMeterRegistry(dynatraceConfig, Clock.SYSTEM);
----

These properties can also be set via the Spring Boot properties file.
It is possible to reference environment variables using the Spring property placeholder notation here.

[source,yml]
----
management.metrics.export.dynatrace:
    enabled: true
    api-version: v2

    # e. g. https://{your-environment-id}.live.dynatrace.com/api/v2/metrics/ingest
    uri: ${ENV_VAR_DT_INGEST_URI}
    api-token: ${ENV_VAR_DT_INGEST_TOKEN}
----

== API Versions

=== API v2 [[bookmark-apiv2]]

When the API version is configured to "v2", the registry will send data using the https://www.dynatrace.com/support/help/dynatrace-api/environment-api/metric-v2/[Metrics API v2].
The v2 exporter does not require any properties to be set except for the version.
In this case, metrics will be exported to the local OneAgent endpoint.
If no OneAgent is running on the target host, it is possible to specify an endpoint and an API token in order to export metrics to that specific endpoint.

*Minimal configuration with a local Dynatrace OneAgent*

In the minimal configuration <<bookmark-oneagent-example, shown above>> (no URI or API token), the v2 exporter will attempt to export to the https://www.dynatrace.com/support/help/how-to-use-dynatrace/metrics/metric-ingestion/ingestion-methods/local-api/[local OneAgent metrics ingest endpoint].
Note that this only works if the a OneAgent is running on the host and the https://www.dynatrace.com/support/help/how-to-use-dynatrace/metrics/metric-ingestion/ingestion-methods/local-api/#enable-the-oneagent-metric-api[local OneAgent Metric API] is available.
If the ingestion port was changed to a custom one, the full endpoint URI has to be provided for the URI property (with API token left empty).

*Configuration with URI and API token*

If no local OneAgent is running on the host or the metrics should be sent to a different endpoint (e.g., a different tenant), the Dynatrace v2 exporter can be configured with an explicit endpoint URI and an https://www.dynatrace.com/support/help/dynatrace-api/basics/dynatrace-api-authentication/[API token].
The https://www.dynatrace.com/support/help/dynatrace-api/basics/dynatrace-api-authentication/[API token] must have the https://www.dynatrace.com/support/help/shortlink/api-authentication#token-permissions["Ingest metrics"] (`metrics.ingest`) permission set.
It is recommended to limit scope to only this permission.

The entire Metrics v2 API endpoint URI has to be specified including its path, i.e., with the path `/api/v2/metrics/ingest` on SaaS and managed deployments, or `/metrics/ingest` for OneAgent endpoints as mentioned in the https://www.dynatrace.com/support/help/dynatrace-api/environment-api/metric-v2/post-ingest-metrics/[documentation].

*Properties available in the v2 exporter*

When using the https://www.dynatrace.com/support/help/dynatrace-api/environment-api/metric-v2/[Dynatrace metrics API v2], additional optional properties can be set:

[source,yml]
----
management.metrics.export.dynatrace:
    enabled: true
    # required to use the properties below
    api-version: v2

    # required if not using a local OneAgent endpoint.
    uri: https://{your-environment-id}.live.dynatrace.com/api/v2/metrics/ingest
    # or https://{your-domain}/e/{your-environment-id}/api/v2/metrics/ingest on Managed

    # It is *not* recommended to put the token into the YAML file directly.
    # It should be read from environment variables or System properties instead,
    # e. g., using `api-token: ${ENV_VAR_DT_INGEST_TOKEN}`
    api-token: YOUR_TOKEN

    # Sets a prefix that is prepended to each exported metric key.
    metric-key-prefix: your.key.prefix

    # If set to true and a local OneAgent is running, retrieves process and host metadata
    # and adds it as additional dimensions to all data points (default: true)
    enrich-with-one-agent-metadata: true

    # Sets an arbitrary number of key-value pairs as default dimensions.
    # Micrometer tags will overwrite these dimensions, if the same key appears twice.
    # Each exported metric will contain these dimensions.
    default-dimensions:
        key1: "value1"
        key2: "value2"

    # The export interval in which metrics are sent to Dynatrace. (default: 60s)
    step: 60s
----

These properties can also be set in code by overwriting the respective methods.

=== API v1 (Legacy)

When the apiVersion is configured to "v1", the registry will send data using the https://www.dynatrace.com/support/help/dynatrace-api/environment-api/metric-v1/custom-metrics/[Dynatrace Timeseries API v1 for custom metrics].
The reported metrics will be assigned to https://www.dynatrace.com/support/help/dynatrace-api/environment-api/topology-and-smartscape/custom-device-api/report-custom-device-metric-via-rest-api/[custom devices] in Dynatrace.
If no apiVersion is specified, it will default to "v1" for backwards-compatibility with earlier setups.

For the v1 API, do not specify the ingest path, but only the base URL of your environment, e. g. `uri: https://{your-environment-id}.live.dynatrace.com`

[source,java]
----
DynatraceConfig dynatraceConfig = new DynatraceConfig() {
    @Override
    public String uri() {
        // The Dynatrace environment URI without any path, e. g.:
        // https://{your-environment-id}.live.dynatrace.com
        return MY_DYNATRACE_URI;
    }

    @Override
    public String apiToken() {
        // It is *not* recommended to place secrets in config files 
        // but rather to read them from env vars, for example.
        return MY_TOKEN;
    }

    @Override
    public String deviceId() {
        return MY_DEVICE_ID;
    }

    @Override
    @Nullable
    public String get(String k) {
        return null;
    }
};
MeterRegistry registry = new DynatraceMeterRegistry(dynatraceConfig, Clock.SYSTEM);
----

`DynatraceConfig` is an interface with a set of default methods. If, in the implementation of `get(String k)`, rather than returning `null` you instead bind it to a property source, you can override the default configuration. For example, Micrometer's Spring Boot support binds properties prefixed with `management.metrics.export.dynatrace` directly to the `DynatraceConfig`:

[source,yml]
----
management.metrics.export.dynatrace:
    enabled: true
    # This is required
    uri: https://your-environment-id.live.dynatrace.com

    # This is required
    api-token: MY_TOKEN

    # This is required
    device-id: sample

    # You will probably want disable Dynatrace publishing in a local development profile.
    enabled: true

    # The interval at which metrics are sent to Dynatrace. The default is 1 minute.
    step: 1m
----
