= Micrometer Influx
Jon Schneider <jschneider@pivotal.io>
:toc:
:sectnums:
:system: influx

The InfluxData suite of tools supports real-time stream processing and storage of time-series data. It supports downsampling, automatically expiring and deleting unwanted data, as well as backup and restore.

Since Micrometer 1.7, the InfluxMeterRegistry supports the 1.x InfluxDB API as well as the v2 API.

== Configuring

Micrometer supports shipping metrics to Influx directly or through Telegraf via the StatsD registry.

=== Direct to Influx

In Gradle:

[source,groovy]
----
implementation 'io.micrometer:micrometer-registry-influx:latest.release'
----

Or in Maven:

[source,xml]
----
<dependency>
  <groupId>io.micrometer</groupId>
  <artifactId>micrometer-registry-influx</artifactId>
  <version>${micrometer.version}</version>
</dependency>
----

Metrics are rate-aggregated and pushed to Influx on a periodic interval. Rate aggregation performed by the registry yields datasets that are quite similar to those produced by Telegraf.

[source, java]
----
InfluxConfig config = new InfluxConfig() {
    @Override
    public Duration step() {
        return Duration.ofSeconds(10);
    }

    @Override
    public String db() {
        return "mydb";
    }

    @Override
    public String get(String k) {
        return null; // accept the rest of the defaults
    }
};
MeterRegistry registry = new InfluxMeterRegistry(config, Clock.SYSTEM);
----

To ship metrics to InfluxDB 2.x, make sure to configure the `org` and `bucket` to write the metrics to, as well as the authentication `token`.

`InfluxConfig` is an interface with a set of default methods. If, in the implementation of `get(String k)`, rather than returning `null`, you instead bind it to a property source, you can override the default configuration. For example, Micrometer's Spring Boot support binds properties prefixed with `management.metrics.export.influx` directly to the `InfluxConfig`:

[source, yaml]
----
management.metrics.export.influx:
    auto-create-db: true # Whether to create the Influx database if it does not exist before attempting to publish metrics to it. (Default: true)
    batch-size: 10000 # Number of measurements per request to use for this backend. If more measurements are found, then multiple requests will be made. (Default: 10000)
    compressed: true # Whether to enable GZIP compression of metrics batches published to Influx. (Default: true)
    connect-timeout: 1s # Connection timeout for requests to this backend. (Default: 1s)
    consistency: one # Write consistency for each point. (Default: one)
    db: mydb # Tag that will be mapped to "host" when shipping metrics to Influx. (Defaut: mydb)
    enabled: true # Whether exporting of metrics to this backend is enabled. (Default: true)
    num-threads: 2 # Number of threads to use with the metrics publishing scheduler. (Default: 2)
    password: mysecret # Login password of the Influx server.
    read-timeout: 10s # Read timeout for requests to this backend. (Default: 10s)
    retention-policy: my_rp # Retention policy to use (Influx writes to the DEFAULT retention policy if one is not specified).
    step: 1m # Step size (i.e. reporting frequency) to use. (Default: 1m)
    uri: http://localhost:8086 # URI of the Influx server. (Default: http://localhost:8086)
    user-name: myusername # Login user of the Influx server.
----

=== Through Telegraf

Telegraf is a StatsD agent expecting a modified flavor of the StatsD line protocol.

In Gradle:

[source,groovy]
----
implementation 'io.micrometer:micrometer-registry-statsd:latest.release'
----

Or in Maven:

[source,xml]
----
<dependency>
  <groupId>io.micrometer</groupId>
  <artifactId>micrometer-registry-statsd</artifactId>
  <version>${micrometer.version}</version>
</dependency>
----

Metrics are shipped immediately over UDP to Telegraf using Telegraf's flavor of the StatsD line protocol.

[source,java]
----
StatsdConfig config = new StatsdConfig() {
    @Override
    public String get(String k) {
        return null;
    }

    @Override
    public StatsdFlavor flavor() {
        return StatsdFlavor.Telegraf;
    }
};

MeterRegistry registry = new StatsdMeterRegistry(config, Clock.SYSTEM);
----
