Micrometer contains a core library with the instrumentation SPI and an in-memory implementation that doesn't export data anywhere, plus a series of modules with implementations for various monitoring systems, and a test module.

To use Micrometer, add the dependency for your monitoring system of choice. For example, for Prometheus:

In Gradle:

[source,groovy]
----
compile 'io.micrometer:micrometer-registry-prometheus:latest.release'
----

Or in Maven:

[source,xml]
----
<dependency>
  <groupId>io.micrometer</groupId>
  <artifactId>micrometer-registry-prometheus</artifactId>
  <version>${micrometer.version}</version>
</dependency>
----

Through Micrometer's composite meter registry (described in greater detail in link:/docs/concepts#_composite_registries["Concepts"]), you may configure more than one registry implementation if you intend to publish metrics to more than one monitoring system.

If you haven't decided on a monitoring system yet and just want to try out the instrumentation SPI, you can add a dependency on `micrometer-core` instead and configure the `SimpleMeterRegistry`.

== Snapshots

Every successful https://app.circleci.com/pipelines/github/micrometer-metrics/micrometer[build] of Micrometer's `main` and maintenance branches (i.e. `1.7.x`) results in the publication of a new snapshot version. You can use the latest snapshot by adding the Maven repository `https://repo.spring.io/libs-snapshot` to your build and using the corresponding snapshot version, e.g. `1.8.0-SNAPSHOT`.
