version: 2.1

orbs:
  cloudfoundry: circleci/cloudfoundry@0.1.73

jobs:
  build:
    working_directory: ~/micrometer-docs
    docker:
      - image: cimg/node:14.15
    steps:
      - checkout
      - restore_cache:
          name: Restore Node Modules Cache
          keys:
            - node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Node Modules Cache
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      # No tests yet...
      # - run:
          # name: Run Tests
          # command: yarn test
      - run:
          name: Run build
          # Compiler warnings are treated as failures in CI environments by the react-scripts build
          # We have one compiler warning that I cannot figure out how to get rid of...
          command: CI=false yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build
            - manifest.yml

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - cloudfoundry/blue_green:
          filters:
            branches:
              only:
                # Note that pull requests are checked out using `pull/` like refs/pull/1279/head -> origin/pull/1279
                - master
          requires:
            - build
          appname: micrometer-docs
          domain: micrometer.io
          endpoint: https://api.run.pcfone.io
          live_subdomain: ''
          manifest: manifest.yml
          org: group-spring
          package: build
          space: micrometer.io
          workspace_path: '.'
