= Spring Boot support
:toc:
:sectnums:
:dimensional: true

WARNING: Spring Boot 1.5.x and Micrometer releases (up to Micrometer 1.3.x) that include the `micrometer-spring-legacy` module are now out of support.
Please upgrade to supported releases of Spring Boot and Micrometer.
See the latest https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-metrics[Spring Boot reference documentation on metrics] for built-in Spring Boot support after Spring Boot 1.5.

== Installing
Micrometer provides a legacy bridge to Spring Boot 1.5.
The following example shows the required dependency in Gradle:

[source,groovy,subs=+attributes]
----
implementation 'io.micrometer:micrometer-spring-legacy:latest.release'
----

The following example shows the required dependency in Maven:

[source,xml,subs=+attributes]
----
<dependency>
  <groupId>io.micrometer</groupId>
  <artifactId>micrometer-spring-legacy</artifactId>
  <version>${micrometer.version}</version>
</dependency>
----

You should add this dependency alongside any registry implementations you want to use, such as `micrometer-registry-prometheus`.

== Configuring

include::spring-configuring.adoc[leveloffset=+1]

== Web monitoring

include::spring-web.adoc[leveloffset=+1]

== Scheduling

include::spring-scheduling.adoc[leveloffset=+1]

== Cache monitoring

include::spring-cache.adoc[leveloffset=+1]

== Data source monitoring

include::spring-datasource.adoc[leveloffset=+1]

== Registering custom metrics
To register custom metrics, you can inject a `MeterRegistry` into your component:

[source,java,indent=0]
----
class Dictionary {
	private List<String> words = new CopyOnWriteArrayList<>();

	public MyComponent(MeterRegistry registry) {
		registry.gaugeCollectionSize("dictionary.size", Tags.empty(), words);
	}

	...
}
----

If you find that you repeatedly instrument a suite of metrics across components or
applications, you can encapsulate this suite in a `MeterBinder` implementation. By
default, metrics from all `MeterBinder` beans are automatically bound to
the Spring-managed `MeterRegistry`.

== Customizing individual metrics

include::spring-meter-filters.adoc[leveloffset=+1]

== With Spring Boot Actuator

include::spring-boot-actuator.adoc[leveloffset=+1]

== Application properties

include::spring-boot-application-properties.adoc[leveloffset=+1]
