= Spring Boot support
Jon Schneider <jschneider@pivotal.io>
:toc:
:sectnums:
:dimensional: true

WARNING: Spring Boot 1.5.x and Micrometer releases (up to Micrometer 1.3.x) that include the `micrometer-spring-legacy` module are now out of support.
Please upgrade to supported releases of Spring Boot and Micrometer.
Refer to the latest https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-metrics[Spring Boot reference documentation on metrics] for built-in Spring Boot support post Spring Boot 1.5.

== Installing
Micrometer provides a legacy bridge to Spring Boot 1.5. To install the required dependency in Gradle:

In Gradle:

[source,groovy,subs=+attributes]
----
compile 'io.micrometer:micrometer-spring-legacy:latest.release'
----

Or in Maven:

[source,xml,subs=+attributes]
----
<dependency>
  <groupId>io.micrometer</groupId>
  <artifactId>micrometer-spring-legacy</artifactId>
  <version>${micrometer.version}</version>
</dependency>
----

This dependency should be added alongside any registry implementations you want to use, e.g. `micrometer-registry-prometheus`.

== Configuring

include::spring-configuring.adoc[leveloffset=+1]

== Web monitoring

include::spring-web.adoc[leveloffset=+1]

== Scheduling

include::spring-scheduling.adoc[leveloffset=+1]

== Cache monitoring

include::spring-cache.adoc[leveloffset=+1]

== Data source monitoring

include::spring-datasource.adoc[leveloffset=+1]

== Registering custom metrics
To register custom metrics, inject `MeterRegistry` into your component:

[source,java,indent=0]
----
class Dictionary {
	private List<String> words = new CopyOnWriteArrayList<>();

	public MyComponent(MeterRegistry registry) {
		registry.gaugeCollectionSize("dictionary.size", Tags.empty(), words);
	}

	...
}
----

If you find that you repeatedly instrument a suite of metrics across components or
applications, you may encapsulate this suite in a `MeterBinder` implementation. By
default, metrics from all `MeterBinder` beans will be automatically bound to
the Spring-managed `MeterRegistry`.

== Customizing individual metrics

include::spring-meter-filters.adoc[leveloffset=+1]

== With Spring Boot Actuator

include::spring-boot-actuator.adoc[leveloffset=+1]

== Application properties

include::spring-boot-application-properties.adoc[leveloffset=+1]
