Spring Boot auto-configures a composite meter registry and adds a registry to the composite for each of the supported implementations that it finds on the classpath. Having a dependency on `micrometer-registry-{system}` in your runtime classpath is enough for Spring Boot to configure the registry. Spring Boot also adds any auto-configured registries to the global static composite registry on the `Metrics` class unless you explicitly tell it not to by setting:

[source,properties]
----
# true by default
management.metrics.use-global-registry=false
----

Leaving configuration of the global registry on lets you collect metrics from libraries that use the static global registry to wire their metrics without doing anything further.

You can control whether a registry implementation is auto-configured through a property, even if it is otherwise present on the classpath:

[source,properties,subs=+attributes]
----
# true by default
management.metrics.export.{system}.enabled=false
----

*Optionally*, you can register any number of `MeterRegistryCustomizer` instances to further configure the registry (such as applying common tags) before any meters are registered with the registry:

[source,java]
----
@SpringBootApplication
public class MyApplication {
    @Bean
    MeterRegistryCustomizer<MeterRegistry> metricsCommonTags() {
      return registry -> registry.config().commonTags("region", "us-east-1");
    }
}
----

You can apply customizations to particular registry implementations by being more specific about the generic type:

[source,java]
----
@SpringBootApplication
public class MyApplication {
    @Bean
    MeterRegistryCustomizer<GraphiteMeterRegistry> graphiteMetricsNamingConvention() {
      return registry -> registry.config().namingConvention(MY_CUSTOM_CONVENTION);
    }
}
----

== Meter Binders

Spring auto-configures the most commonly used binders.

The `JvmMemoryMetrics` binder is automatically configured to record memory and buffer pool utilization. In the presence of Logback, the `LogbackMetrics` binder is also configured to record the number of events logged to Logback at each level. Finally, `UptimeMetrics` reports a gauge for uptime and a fixed gauge representing the application's absolute start time.

To register other binders with the registry, add them as beans to your application context.

== Atlas

The following listing describes the most common configuration properties you may want to change and their default values
(from any property source, such as `application.yml`):

[source,properties]
----
# The location of your Atlas server
management.metrics.export.atlas.uri=http://localhost:7101/api/v1/publish

# You will probably want disable Atlas publishing in a local development profile.
management.metrics.export.atlas.enabled=true # default is true

# The interval at which metrics are sent to Atlas. See Duration.parse for the expected format.
# The default is 1 minute.
management.metrics.export.atlas.step=PT1M
----

For a full list of configuration properties that can influence Atlas publishing, see
[`com.netflix.spectator.atlas.AtlasConfig`](https://github.com/Netflix/spectator/blob/master/spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java) in Netflix's API documentation.

== Prometheus

By default, if Spring Boot Actuator is on the classpath, an actuator endpoint is wired to `/prometheus` to present a Prometheus scrape with the appropriate format.

To add actuator if it is not already present on your classpath in Gradle:

[source,groovy]
----
implementation 'org.springframework.boot:spring-boot-starter-actuator'
----

To add actuator if it is not already present on your classpath in Maven:

[source,xml]
----
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
----

The following example adds `scrape_config` to `prometheus.yml`:

[source,yml]
----
scrape_configs:
  - job_name: 'spring'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['HOST:PORT']
----

If you want the endpoint to use a different path, add the following property:

[source,properties]
----
endpoints.prometheus.path=micrometheus
----

NOTE: By default, the endpoint is secured, so either include authentication in your Prometheus scrape endpoint or unsecure the prometheus endpoint by setting a property, such as `management.security.enabled=false`

== Datadog

The Datadog registry pushes metrics to datadoghq periodically. The following listing shows
the most common configuration properties you may want to change and their default values
(from any property source, such as `application.yml`):

[source,properties]
----
management.metrics.export.datadog.api-key=YOURKEY

# Needed to send meter-level metadata like descriptions and base units to Datadog, but not strictly required.
management.metrics.export.datadog.application-key=YOURKEY

# You will probably want disable Datadog publishing in a local development profile.
management.metrics.export.datadog.enabled=true # default is true

# The interval at which metrics are sent to Datadog. See Duration.parse for the expected format.
# The default is 10 seconds, which matches the Datadog Agent publishes at.
management.metrics.export.datadog.step=PT10S
----

For a full list of configuration properties that can influence Datadog publishing, see
[`io.micrometer.core.instrument.datadog.DatadogConfig`](https://github.com/micrometer-metrics/micrometer/blob/main/implementations/micrometer-registry-datadog/src/main/java/io/micrometer/datadog/DatadogConfig.java).

== StatsD

The StatsD registry eagerly pushes metrics over UDP to a StatsD agent. The following listing shwos the most
common configuration properties you may want to change:

[source,properties]
----
management.metrics.export.statsd.enabled=true # default is true
management.metrics.export.statsd.flavor=etsy # or datadog, telegraf
management.metrics.export.statsd.host=localhost
management.metrics.export.statsd.port=8125
----
