If you need to apply customizations to specific `Meter` instances, you can use the `io.micrometer.core.instrument.config.MeterFilter` interface. By default, all `MeterFilter` beans are automatically applied to Spring's managed `MeterRegistry`.

For example, if you want to rename the `mytag.region` tag to `mytag.area` for all meter IDs that begin with `com.example`, you can use the following:

[source,java]
----
@Bean
public MeterFilter renameRegionTagMeterFilter() {
	return MeterFilter.renameTag("com.example", "mytag.region", "mytag.area");
}
----

== Per-meter properties
In addition to `MeterFilter` beans, you can apply a limited set of customizations on a per-meter basis by using properties. Per-meter customizations apply to any and all meter IDs that start with the given name. For example, the following disables any meters that have an ID that starts with `example.remote`

[source,properties]
----
management.metrics.enable.example.remote=false
----

The following properties allow per-meter customization:

.Per-meter customizations
|===
| Property | Description

| `management.metrics.enable`
| Whether to prevent meters from emitting any metrics.

| `management.metrics.distribution.percentiles-histogram`
| Whether to publish a histogram suitable for computing aggregable (across dimensions)
percentile approximations.

| `management.metrics.distribution.percentiles`
| Publish percentile values computed in your application

| `management.metrics.distribution.sla`
| Publish a cumulative histogram with buckets defined by your SLAs.

|===

In Spring Boot 1.5.x, you must escape the metric name prefix following any of these properties, as follows:

[source,txt]
----
management.metrics.distribution.percentiles-histogram[http.server.requests]=true
----

The escaping looks the same in both `.properties` and `.yml` formats. This escaping is _not_ required in Spring Boot 2.

For more details on the concepts behind `percentiles-histogram`, `percentiles` and `sla`,
see the https://micrometer.io/docs/concepts#_histograms_and_percentiles["Histograms
and Percentiles" section] of the Concepts documentation.
