:noheader:
[[micrometer-documentation]]
= Micrometer Documentation

== Vendor-neutral application observability facade

Micrometer provides a simple facade over the instrumentation clients for the most popular observability systems, allowing you to instrument your JVM-based application code without vendor lock-in.
Think SLF4J, but for observability.

== Projects

Micrometer consists of various projects that have their own release cycle. Micrometer does not come with a release train BOM (Bill of Materials) but for your convenience we are grouping the corresponding projects with their compatible versions.

Micrometer `{micrometer-docs-version}` release train consists of the following projects:

- https://micrometer.io/docs/context-propagation/reference/{context-propagation-version}/index.html[Micrometer Context Propagation {context-propagation-version}]
- https://micrometer.io/docs/micrometer/reference/{micrometer-version}/index.html[Micrometer Core {micrometer-version}]
- https://micrometer.io/docs/tracing/reference/{tracing-version}/index.html[Micrometer Tracing {tracing-version}]
- https://micrometer.io/docs/docs-generation/reference/{micrometer-docs-generation-version}/index.html[Micrometer Docs Generator {micrometer-docs-generation-version}]
