A gauge is a handle to get the current value. Typical examples for gauges would be the size of a collection or map or number of threads in a running state.

TIP: Gauges are useful for monitoring things with natural upper bounds. We don't recommend using a gauge to monitor things like request count, as they can grow without bound for the duration of an application instance's life.

Micrometer takes the stance that gauges should be sampled and not set, so there is no information about what might have occurred between samples. After all, any intermediate values set on a gauge are lost by the time the gauge value is reported to a metrics backend anyway, so there seems to be little value in setting those intermediate values in the first place.

If it helps, think of a `Gauge` as a "heisen-gauge" - a meter that only changes when it is observed. Every other meter type provided out-of-the-box accumulate intermediate counts toward the point where the data is sent to the metrics backend.

The `MeterRegistry` interface contains methods for building gauges to observe numeric values, functions, collections, and maps.

[source, java]
----
AtomicInteger n = registry.gauge("numberGauge", new AtomicInteger(0)); <1>
List<String> list = registry.gauge("listGauge", Collections.emptyList(), new ArrayList<>(), List::size); <2>
List<String> list = registry.gaugeCollectionSize(new ArrayList<>(), "listGauge2"); <3>
Map<String, Integer> map = registry.gaugeMapSize(new HashMap<>(), "mapGauge");
----
<1> The simplest form of gauge monitors any `Number` instance. Note that unlike other meter types you don't get a reference to the `Gauge` when creating one, but rather the thing being observed. This is because of the heisen-gauge principal; the gauge is self sufficient once created, so you should never need to interact with it. This allows us to give you back only the instrumented object, which allows for quick one liners that both create the object to be observed and set up metrics around it.
<2> A slightly more common form of gauge is one that monitors some non-numeric object. The last argument establishes the function that is used to determine the value of the gauge when the gauge is observed.
<3> A more convenient form of (2) for when you simply want to monitor collection size.

All of the different forms of creating a gauge maintain only a weak reference to the object being observed, so as not to prevent garbage collection of the object.

The interface contains a fluent builder for gauges:

[source, java]
----
Gauge gauge = Gauge
    .builder("gauge", myObj, myObj::gaugeValue)
    .description("a description of what this gauge does") // optional
    .tags("region", "test") // optional
    .register(registry);
----

Generally the returned `Gauge` instance is not useful except in testing, as the gauge is already set up to track a value automatically upon registration.