Timers and distribution summaries support collecting data to observe their percentile distributions. There are two main approaches to viewing percentiles:

1. *Percentile histograms* - Micrometer accumulates values to an underlying histogram and ships a predetermined set of buckets to the monitoring system. The monitoring system's query language is responsible for calculating percentiles off of this histogram. Currently, only Prometheus and Atlas support histogram-based percentile approximations based on histograms, via `histogram_quantile` and `:percentile`, respectively. If targeting Prometheus or Atlas, prefer this approach, since you can aggregate the histograms across dimensions (by simply summing the values of the buckets across a set of dimensions) and derive an aggregable percentile from the histogram.
2. *Client-side percentiles* - Micrometer computes a percentile approximation for each set meter id (set of name and tags) and ships the percentile value to the monitoring system. This is not as flexible as a percentile histogram because it is not possible to aggregate percentile approximations across tags. Nevertheless, it provides some level of insight into percentile distributions for monitoring systems that don't support server-side percentile calculation based on a histogram.

Here is an example of building a timer with a histogram:

[source,java]
----
Timer.builder("my.timer")
   .publishPercentiles(0.5, 0.95) // median and 95th percentile
   .publishPercentileHistogram()
   .sla(Duration.ofMillis(100))
   .minimumExpectedValue(Duration.ofMillis(1))
   .maximumExpectedValue(Duration.ofSeconds(10))
----

1. `publishPercentiles` - This is used to publish percentile values computed in your app. These values are non-aggregable across dimensions.
2. `publishPercentileHistogram` - This is used to publish a histogram suitable for computing aggregable (across dimension) percentile approximations in Prometheus using `histogram_quantile` and Atlas using `:percentile`. The buckets in the resulting histogram are preset by Micrometer based on a generator that has been determined empirically by Netflix to yield a reasonable error bound on most real world timers and distribution summaries. The generator yields 276 buckets by default, but Micrometer only ships those that are within the range set by minimumExpectedValue and maximumExpectedValue, inclusive. Micrometer clamps timers by default to a range of 1 millisecond to 1 minute, yielding 73 histogram buckets per timer dimension. publishPercentilesHistogram has no effect on systems that do not support aggregable percentile approximations -- no histogram is shipped for these systems.
3. `sla` - Publish a cumulative histogram with buckets defined by your SLAs. Used in concert with `publishPercentileHistogram` on a monitoring system that supports aggregable percentiles, this setting adds additional buckets to the published histogram. Used on a system that does not support aggregable percentiles, this setting causes a histogram to be published with only these buckets.
4. `minimumExpectedValue/maximumExpectedValue` - Controls the number of buckets shipped by publishPercentileHistogram as well as controlling the accuracy and memory footprint of the underlying HdrHistogram structure.

Since shipping percentiles to the monitoring system generates additional time series, it is generally preferable to *not* configure them in core libraries that are included as dependencies in apps. Instead, apps can turn on this behavior for some set of timers/distribution summaries via a meter filter.

For example, suppose we have a handful of timers in a common library. We've prefixed these timer names with `myservice`:

[source,java]
----
registry.timer("myservice.http.requests").record(..);
registry.timer("myservice.db.requests").record(..);
----

We can turn on client-side percentiles for both timers via a meter filter:

[source,java]
----
registry.config().meterFilter(
    new MeterFilter() {
        @Override
        public HistogramConfig configure(Meter.Id id, HistogramConfig config) {
            if(id.getName().startsWith("myservice")) {
                return HistogramConfig.builder()
                    .percentiles(0.95)
                    .build()
                    .merge(config);
            }
            return config;
        }
    });
----