= Concepts
:toc:
:sectnums:
:dimensional: true

== Purpose

Micrometer is a metrics instrumentation library for JVM-based applications. It provides a simple facade over the instrumentation clients for the most popular monitoring systems, letting you instrument your JVM-based application code without vendor lock-in. It is designed to add little to no overhead to your metrics collection activity while maximizing the portability of your metrics effort.

Starting from Micrometer 1.10, Micrometer provides the link:../docs/observation[Observation API] and a plugin mechanism that allows you to add capabilities including the tracing features. You can read more about this in the link:../docs/tracing[Micrometer Tracing documentation].

For better understanding the differences among these different types of systems (Metrics, Distributed Tracing, and Logging) we recommend Adrian Cole's talk, titled https://www.dotconferences.com/2017/04/adrian-cole-observability-3-ways-logging-metrics-tracing[Observability
3 Ways]. To learn more about Micrometer Observation API we recommend Tommy Ludwig's and Marcin Grzejszczak's talk, titled https://www.youtube.com/watch?v=fh3VbrPvAjg[Observability of Your Application].

== Dependencies

The `micrometer-core` module aims to have minimal dependencies. It does not require any third-party (non-Micrometer) dependencies on the classpath at compile time for applications using Micrometer.

Use of the link:#_pause_detection[pause detection] feature requires the https://github.com/LatencyUtils/LatencyUtils[LatencyUtils] dependency to be available on the classpath at runtime. If your application does not use the pause detection feature, you can exclude LatencyUtils from your runtime classpath.

https://github.com/HdrHistogram/HdrHistogram[HdrHistogram] is needed on the classpath at runtime if you use link:#_histograms_and_percentiles[client-side percentiles]. If you are not using client-side percentiles, you may exclude HdrHistogram from your application's runtime classpath.

== Supported Monitoring Systems

include::implementations.adoc[leveloffset=+1]

== Registry

include::registry.adoc[leveloffset=+1]

== Meters

include::meters.adoc[leveloffset=+1]

== Naming Meters

include::naming.adoc[leveloffset=+1]

== Meter Filters

include::meter-filters.adoc[leveloffset=+1]

[[rate-aggregation]]
== Rate Aggregation

include::rate-aggregation.adoc[leveloffset=+1]

== Counters

include::counters.adoc[leveloffset=+1]

== Gauges

include::gauges.adoc[leveloffset=+1]

== Timers

include::timers.adoc[leveloffset=+1]

== Distribution Summaries

include::distribution-summaries.adoc[leveloffset=+1]

== Long Task Timers

include::long-task-timers.adoc[leveloffset=+1]

== Histograms and Percentiles

include::histogram-quantiles.adoc[leveloffset=+1]
