Micrometer employs a naming convention that separates lowercase words with a '.' (dot) character. Different monitoring systems have different recommendations regarding naming convention, and some naming conventions may be incompatible for one system and not another. Each Micrometer implementation for a monitoring system comes with a naming convention that transforms lowercase dot notation names to the monitoring system's recommended naming convention. Additionally, this naming convention implementation sanitizes metric names and tags of special characters that are disallowed by the monitoring system. You can override the default naming convention for a registry by implementing `NamingConvention` and setting it on the registry with:

[source,java]
----
registry.config().namingConvention(myCustomNamingConvention);
----

With naming conventions in place, the following timer registered in Micrometer looks good natively in a wide variety of monitoring systems:

[source,java]
----
registry.timer("http.server.requests");
----

1. Prometheus - `http_server_requests_duration_seconds`
2. Atlas - `httpServerRequests`
3. Graphite - `http.server.requests`
4. InfluxDB - `http_server_requests`

By adhering to Micrometer's lowercase dot notation convention, you guarantee the maximum degree of portability for your metric names across monitoring systems.

== Tag naming

TIP: It is recommended to follow the same lowercase dot notation described for meter names when naming tags. Utilizing this consistent naming convention for tags allows for better translation into the respective monitoring system's idiomatic naming schemes.

Suppose we are trying to measure the number of http requests and the number of database calls.

*Recommended approach*

[source,java]
----
registry.counter("database.calls", "db", "users")
registry.counter("http.requests", "uri", "/api/users")
----

This variant provides enough context so that if just the name is selected the value can be reasoned about and is at least potentially meaningful. For example if we select `database.calls` we can see the total number of calls to all databases. Then we can group by or select by `db` to drill down further or perform comparative analysis on the contribution of calls to each database.

*Bad approach*

[source,java]
----
registry.counter("calls",
    "class", "database",
    "db", "users");

registry.counter("calls",
    "class", "http",
    "uri", "/api/users");
----

In this approach, if we select `calls` we will get a value that is an aggregate of the number of calls to the database and to our API endpoint. This time series is not useful without further dimensional drill-down.

== Common tags

Common tags can be defined at the registry level and are added to every metric reported to the monitoring system. This is generally used for dimensional drill-down on the operating environment like host, instance, region, stack, etc.

[source,java]
----
registry.config().commonTags("stack", "prod", "region", "us-east-1");
registry.config().commonTags(Arrays.asList(Tag.of("stack", "prod"), Tag.of("region", "us-east-1"))); // equivalently
----

Calls to `commonTags` append additional common tags.

[IMPORTANT]
====
Common tags generally have to be added to the registry _before_ any (possibly autoconfigured) meter binders. Depending on your environment there are different ways to achieve this.

If you are using Spring Boot you can register a `MeterRegistryCustomizer` callback interface as a bean to add your common tags. Please consult the
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.metrics.getting-started[Spring Boot Reference Documentation] for more information.
====

== Tag values

Tag values must be non-null.

WARNING: Beware of the potential for tag values coming from user-supplied sources to blow up the cardinality of a metric. You should always carefully normalize and bound user-supplied input. Sometimes the cause is sneaky. Consider the URI tag for recording HTTP requests on service endpoints. If we don't constrain 404's to a value like NOT_FOUND, the dimensionality of the metric would grow with each resource that can't be found.
