Micrometer employs a naming convention that separates words with '.'. Because different monitoring systems have different recommendations regarding naming convention, and some naming conventions may actually be breaking for one system and not another, each Micrometer implementation for a monitor system packs with a naming convention that transforms dot notation names to the recommended naming convention. Additionally, this naming convention implementation sanitizes names and tags of special characters that are disallowed by the monitoring system they are designed for. You can override the default naming convention for a registry if you'd like by implementing `NamingConvention` and setting it on the registry with:

[source,java]
----
registry.config().namingConvention(myCustomNamingConvention);
----

With naming conventions in place, the following timer registered in Micrometer looks good natively in a wide variety of monitoring systems:

[source,java]
----
registry.timer("http.server.requests");
----

1. Prometheus - `http_server_requests_duration_seconds`
2. Atlas - `httpServerRequests`
3. Graphite - `http.server.requests`
4. InfluxDB - `http_server_requests`

By adhering to Micrometer's dot notation convention, you guarantee the maximum degree of portability for your metric names across monitoring systems.

== Tag naming

Suppose we are trying to measure the number of http requests and the number of database calls.

*Recommended approach*

[source,java]
----
registry.counter("database.calls", "db", "users")
registry.counter("http.requests", "uri", "/api/users")
----

This variant provides enough context so that if just the name is selected the value can be reasoned about and is at least potentially meaningful. For example if we select `database.calls` we can see the total number of calls to all databases. Then we can group by or select by `db` to drill down further or perform comparative analysis on the contribution of calls to each database.

*Bad approach*

[source,java]
----
registry.counter("calls",
    "class", "database",
    "db", "users");

registry.counter("calls",
    "class", "http",
    "uri", "/api/users");
----

In this approach, if we select `calls` we will get a value that is an aggregate of the number of calls to the database and to our API endpoint. This time series is not useful without further dimensional drill-down.

== Common tags

Common tags can be defined at the registry level and are added to every metric reported to the monitoring system. This is generally used for dimensional drill-down on the operating environment like host, instance, region, stack, etc.

[source,java]
----
registry.config().commonTags("stack", "prod", "region", "us-east-1");
registry.config().commonTags(Arrays.asList(Tag.of("stack", "prod"), Tag.of("region", "us-east-1"))); // equivalently
----

Calls to `commonTags` append additional common tags.

IMPORTANT: If you are in the Spring environment, add common tags by adding a `MeterRegistryCustomizer` bean to be sure that common tags are applied before autoconfigured meter binders.

== Tag values

WARNING: Beware of the potential for tag values coming from user-supplied sources to blow up the cardinality of a metric. You should always carefully normalize and bound user-supplied input. Sometimes the cause is sneaky. Consider the URI tag for recording HTTP requests on service endpoints. If we don't constrain 404's to a value like NOT_FOUND, the dimensionality of the metric would grow with each resource that can't be found.
