A `Meter` is the interface for collecting a set of measurements (which we individually call metrics) about your application. Meters in Micrometer are created from and held in a `MeterRegistry`. Each supported monitoring system has an implementation of `MeterRegistry`. How a registry is created varies for each implementation.

Micrometer packs with a `SimpleMeterRegistry` that holds the latest value of each meter in memory and doesn't export the data anywhere. If you don't yet have a preferred monitoring system, you can get started playing with metrics by using the simple registry:

[source,java]
----
MeterRegistry registry = new SimpleMeterRegistry();
----

NOTE: A `SimpleMeterRegistry` is autowired for you in Spring-based apps.

== Composite registries

Micrometer provides a `CompositeMeterRegistry` to which multiple registries can be added, allowing you to publish metrics to more than one monitoring system simultaneously.

[source,java]
----
CompositeMeterRegistry composite = new CompositeMeterRegistry();

Counter compositeCounter = composite.counter("counter");
compositeCounter.increment(); <1>

SimpleMeterRegistry simple = new SimpleMeterRegistry();
composite.add(simple); <2>

compositeCounter.increment(); <3>
----

1. Increments are NOOPd until there is a registry in the composite. The counter's count will still yield 0 at this point.
2. A counter named "counter" is registered to the simple registry.
3. The simple registry counter is incremented, along with counters for any other registries in the composite.

== Global registry

Micrometer provides a static global registry `Metrics.globalRegistry` and a set of static builders for generating meters based on this registry. `globalRegistry` is a composite registry.

[source,java]
----
class MyComponent {
    Counter featureCounter = Metrics.counter("feature", "region", "test"); <1>

    void feature() {
        featureCounter.increment();
    }

    void feature2(String type) {
        Metrics.counter("feature.2", "type", type).increment(); <2>
    }
}

class MyApplication {
    void start() {
        // wire your monitoring system to global static state
        Metrics.addRegistry(new SimpleMeterRegistry()); <3>
    }
}
----

1. Wherever possible (and especially where instrumentation performance is critical), store `Meter` instances in fields to avoid a lookup on their name/tags on each use.
2. When tags need to be determined from local context, you have no choice but to construct/lookup the Meter inside your method body. The lookup cost is just a single hash lookup, so will be acceptable for most uses.
3. It is OK to add registries _after_ meters have been created like `Metrics.counter(...)`. These meters will be added to each registry as it is bound to the global composite.