Micrometer Tracing comes with `micrometer-tracing-test` and `micrometer-tracing-integration-test` modules.

For unit tests it provides a `SimpleTracer` that is a test implementation of a `Tracer`.

For the integration tests it provides a `SampleTestRunner` mechanism that you can hook into your samples.
It will

* Configure a OpenZipkin Brave Tracer
** Set it up with Tanzu Observability by Wavefront Reporter
** Set it up with OpenZipkin Zipkin Reporter
* Configure a OpenTelemetry Tracer
** Set it up with Tanzu Observability by Wavefront Exporter
** Set it up with OpenZipkin Zipkin Exporter
* Run all the combinations above against the user code and running infrastructure

== Installing

The following example shows the required dependency in Gradle (assuming that Micrometer Tracing BOM has been added):

[source,groovy,subs=+attributes]
----
testImplementation 'io.micrometer:micrometer-tracing-test' // for unit tests
testImplementation 'io.micrometer:micrometer-tracing-integration-test' // for integration tests
----

The following example shows the required dependency in Maven (assuming that Micrometer Tracing BOM has been added):

[source,xml,subs=+attributes]
----
<dependency>
    <groupId>io.micrometer</groupId>
    <artifactId>micrometer-tracing-test</artifactId> <!-- For unit tests -->
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.micrometer</groupId>
    <artifactId>micrometer-tracing-integration-test</artifactId> <!-- For integration tests -->
    <scope>test</scope>
</dependency>
----

== Running Observation Unit Tests

In your instrumentation code you will depend on `io.micrometer:micrometer-observation` module only. To run unit tests of `Observation`s, you should just use `io.micrometer:micrometer-observation-test`.

Let's say that you have the following production code. It will create an observation with 2 tags (low and high) and then call `observe` that will start the observation, put it in scope, close the scope and stop the observation.

[source,java,subs=+attributes]
----
class Example {

    private final ObservationRegistry registry;

    Example(ObservationRegistry registry) {
        this.registry = registry;
    }

    void run() {
        Observation.createNotStarted("foo", registry)
                .lowCardinalityTag("lowTag", "lowTagValue")
                .highCardinalityTag("highTag", "highTagValue")
                .observe(() -> System.out.println("Hello"));
    }
}
----

To unit test this code you can use the `TestObservationRegistry` class.

[source,java,subs=+attributes]
----
    // create a test registry in your tests
    TestObservationRegistry registry = TestObservationRegistry.create();

    @Test
    void should_assert_your_observation() {
        // run your production code with the TestObservationRegistry
        new Example(registry).run();

        // check your observation
        TestObservationRegistryAssert.assertThat(registry)
                .doesNotHaveAnyRemainingCurrentObservation()
                .hasObservationWithNameEqualTo("foo").that()
                    .hasHighCardinalityTag("highTag", "highTagValue")
                    .hasLowCardinalityTag("lowTag", "lowTagValue")
                    .hasBeenStarted()
                    .hasBeenStopped();
    }
----

== Running Tracing Unit Tests

To run unit tests of your custom handler you may want to use the `SimpleTracer` test `Tracer` implementation. Let's assume the following custom `TracingObservationHandler`.

[source,java,subs=+attributes]
-----
public class MyTracingObservationHandler implements TracingObservationHandler<MyCustomHandlerContext> {

	private final Tracer tracer;

	public MyTracingObservationHandler(Tracer tracer) {
		this.tracer = tracer;
	}

    @Override public void onStart(CustomContext context) {
        String databaseName = context.getDatabaseName();
        Span.Builder builder = this.tracer.spanBuilder().kind(Span.Kind.CLIENT)
                .remoteServiceName(databaseName);
        getTracingContext(context).setSpan(builder.start());
    }

    @Override public void onError(CustomContext context) {
        getTracingContext(context).getSpan().error(context.getError().get());
    }

    @Override public void onStop(CustomContext context) {
        Span span = getRequiredSpan(context);
        span.name(context.getContextualName());
        tagSpan(context, span);
        span.end();
    }

    @Override public boolean supportsContext(Observation.Context context) {
        return context instanceof CustomContext;
    }
}
-----

To verify whether the spans got properly created we can use the `SimpleTracer` as follows:

[source,java,subs=+attributes]
-----
class SomeComponentThatIsUsingMyTracingObservationHandlerTests {

	ObservationRegistry registry = ObservationRegistry.create();

	SomeComponent someComponent = new SomeComponent(registry);

	SimpleTracer simpleTracer = new SimpleTracer();

	MyTracingObservationHandler handler = new MyTracingObservationHandler(simpleTracer);

    @BeforeEach
    void setup() {
        registry.config().observationHandler(handler);
    }

    @Test
    void should_store_a_span() {
        someComponent.doSthThatShouldCreateSpans(); // this code will call actual Observation API

        TracerAssert.assertThat(simpleTracer)
                .onlySpan()
                    .hasNameEqualTo("insert user")
                    .hasSpanWithKindEqualTo(Span.Kind.CLIENT)
                    .hasRemoteServiceNameEqualTo("mongodb-database")
                    .hasTag("mongodb.command", "insert")
                    .hasTag("mongodb.collection", "user")
                    .hasTagWithKey("mongodb.cluster_id")
                    .assertThatThrowable()
                        .isInstanceOf(IllegalAccessException.class)
                        .backToSpan()
                    .hasIpThatIsBlank()
                    .hasPortThatIsNotSet();
    }
}
-----

== Running integration tests

The following example shows how you can run your code to test your integrations

* by asserting spans that were stored without emitting them to a reporting system
* against running Tanzu Observability by Wavefront instance (this option turns on when you have passed the Wavefront related configuration in the constructor - otherwise the test will be disabled)
* against running Zipkin instance (this option turns on when Zipkin is running - otherwise the test will be disabled)

[source,java,subs=+attributes]
-----
class ObservabilitySmokeTest extends SampleTestRunner {

	ObservabilitySmokeTest() {
		super(SamplerRunnerConfig
				.builder()
				.wavefrontApplicationName("my-app")
				.wavefrontServiceName("my-service")
				.wavefrontToken("...")
				.wavefrontUrl("...")
				.zipkinUrl("...") // defaults to localhost:9411
				.build());
	}

	@Override
	public BiConsumer<BuildingBlocks, Deque<ObservationHandler>> customizeObservationHandlers() {
		return (bb, handlers) -> {
			ObservationHandler defaultHandler = handlers.removeLast();
			handlers.addLast(new ReactorNettyTracingObservationHandler(bb.getTracer()));
			handlers.addLast(defaultHandler);
			handlers.addFirst(new ReactorNettyHttpClientTracingObservationHandler(bb.getTracer(), bb.getHttpClientHandler()));
			handlers.addFirst(new ReactorNettyHttpServerTracingObservationHandler(bb.getTracer(), bb.getHttpServerHandler()));
		};
	}

	@Override
	public SampleTestRunnerConsumer yourCode() {
		byte[] bytes = new byte[1024 * 8];
		Random rndm = new Random();
		rndm.nextBytes(bytes);

		return (bb, meterRegistry) -> {
			Http11SslContextSpec serverCtxHttp11 = Http11SslContextSpec.forServer(ssc.certificate(), ssc.privateKey());
			Http11SslContextSpec clientCtxHttp11 =
					Http11SslContextSpec.forClient()
							.configure(builder -> builder.trustManager(InsecureTrustManagerFactory.INSTANCE));

			HttpClient client =
					HttpClient.create()
							.wiretap(true)
							.metrics(true, Function.identity())
							.secure(spec -> spec.sslContext(clientCtxHttp11));

			// Make a test to localhost
			DisposableServer server =
					HttpServer.create()
							.wiretap(true)
							.metrics(true, Function.identity())
							.secure(spec -> spec.sslContext(serverCtxHttp11))
							.route(r -> r.post("/post", (req, res) -> res.send(req.receive().retain())))
							.bindNow();

			String content = new String(bytes, Charset.defaultCharset());
			String response =
					client.port(server.port())
							.host("localhost")
							.post()
							.uri("/post")
							.send(ByteBufMono.fromString(Mono.just(content)))
							.block();

			assertThat(response).isEqualTo(content);

			client.secure()
					.post()
					.uri("https://httpbin.org/post")
					.send(ByteBufMono.fromString(Mono.just(content)))
					.responseContent()
					.aggregate()
					.asString()
					.block();

			// @formatter:off
      SpansAssert.assertThat(bb.getFinishedSpans())
              .haveSameTraceId()
              .hasNumberOfSpansEqualTo(8)
              .hasNumberOfSpansWithNameEqualTo("handle", 4)
                .forAllSpansWithNameEqualTo("handle", span -> span.hasTagWithKey("rsocket.request-type"))
              .hasASpanWithNameIgnoreCase("request_stream")
                .thenASpanWithNameEqualToIgnoreCase("request_stream")
                .hasTag("rsocket.request-type", "REQUEST_STREAM")
                .backToSpans()
              .hasASpanWithNameIgnoreCase("request_channel")
                .thenASpanWithNameEqualToIgnoreCase("request_channel")
                .hasTag("rsocket.request-type", "REQUEST_CHANNEL")
                .backToSpans()
              .hasASpanWithNameIgnoreCase("request_fnf")
                .thenASpanWithNameEqualToIgnoreCase("request_fnf")
                .hasTag("rsocket.request-type", "REQUEST_FNF")
                .backToSpans()
              .hasASpanWithNameIgnoreCase("request_response")
                .thenASpanWithNameEqualToIgnoreCase("request_response")
                .hasTag("rsocket.request-type", "REQUEST_RESPONSE");

      MeterRegistryAssert.assertThat(registry)
              .hasTimerWithNameAndTags("rsocket.response", Tags.of(Tag.of("error", "none"), Tag.of("rsocket.request-type", "REQUEST_RESPONSE")))
              .hasTimerWithNameAndTags("rsocket.fnf", Tags.of(Tag.of("error", "none"), Tag.of("rsocket.request-type", "REQUEST_FNF")))
              .hasTimerWithNameAndTags("rsocket.request", Tags.of(Tag.of("error", "none"), Tag.of("rsocket.request-type", "REQUEST_RESPONSE")))
              .hasTimerWithNameAndTags("rsocket.channel", Tags.of(Tag.of("error", "none"), Tag.of("rsocket.request-type", "REQUEST_CHANNEL")))
              .hasTimerWithNameAndTags("rsocket.stream", Tags.of(Tag.of("error", "none"), Tag.of("rsocket.request-type", "REQUEST_STREAM")));
      // @formatter:on
		};
	}
}
-----
