A popular way to record them is storing the start state in a `Observation` instance and stop it when the event has ended. In this case, the `Observation` does the recording and reports the data through the `ObservationHandler`s. +
Recording such measurements could look like this:

[source,java]
----
Timer.Sample sample = Timer.start(registry);
try {
// do some work here
} finally {
sample.stop(Timer.builder("my.timer"));
}
----

If you want to have more observation options (such as metrics and tracing out of the box plus anything else you will plug in) then you'll need to rewrite that code to use the `Observation` API.

[source,java]
----
ObservationRegistry registry = new SimpleMeterRegistry();
Observation observation = Observation.start("my.operation", registry);
try (Observation.Scope scope = observation.openScope()) {
    doSomeWorkHere();
}
finally {
    observation.stop();
}
----

One of the new features in Micrometer 2.0 is the ability of registering "handlers" (`ObservationHandler`) that are notified about the lifecycle event of an observation (e.g.: you can run custom code when an observation is stopped/started).
Using this feature lets you add tracing capabilities to your existing metrics instrumentation (see: `DefaultTracingObservationHandler`). The implementation of these handlers does not need to be tracing related, it is completely up to you how you are going to implement them (e.g.: you can add logging capabilities) if you want.

=== Observation.Context

In order to pass information between the instrumented code and the handler (or between handler methods, e.g.: `onStart` and `onStop`), you can utilize a `Observation.Context`. A `Observation.Context` is a `Map`-like container that can store values for you while your handler can access the data inside the context.

=== ObservationHandler Example

Based on this, we can implement a simple handler that lets the users know about its invocations by printing them out to `stdout`.

[source,java]
----
class SimpleHandler implements ObservationHandler<Observation.Context> {
    @Override
    public void onStart(Observation.Context context) {
        System.out.println("START " + "data: " + context.get(String.class));
    }

    @Override
    public void onError(Observation.Context context) {
        System.out.println("ERROR " + "data: " + context.get(String.class) + ", error: " + context.getError().get());
    }

    @Override
    public void onStop(Observation.Context context) {
        System.out.println("STOP  " + "data: " + context.get(String.class));
    }

    @Override
    public boolean supportsContext(Timer.HandlerContext handlerContext) {
        return true; // you can decide if your handler should be invoked for this context object or not
    }
}
----

You can register this handler like this:

[source,java]
----
ObservationRegistry registry = new SimpleMeterRegistry();
registry.observationConfig().observationHandler(new SimpleHandler());
----

And instrument your codebase. Using the `scoped` method example:

[source,java]
----
// using a context is optional, you can call start without it: Observation.start(name, registry)
ObservationRegistry registry = new SimpleMeterRegistry();
Observation.Context context = new Observation.Context().put(String.class, "test");
Observation observation = Observation.start("my.operation", context, registry);
try (Observation.Scope scope = observation.openScope()) {
    doSomeWorkHere();
}
finally {
    observation.stop();
}
----

Fully taking control of the scoping mechanism.

[source,java]
----
// using a context is optional, you can call start without it: Observation.start(name, registry)
ObservationRegistry registry = new SimpleMeterRegistry();
Observation.Context context = new Observation.Context().put(String.class, "test");
Observation observation = Observation.start("my.operation", context, registry);
try (Observation.Scope scope = observation.openScope()) {
    doSomeWorkHere();
}
catch (Exception ex) {
    sample.error(ex); // and don't forget to handle exceptions
    throw ex;
}
finally {
    observation.stop();
}
----

=== Observation.TagsProvider Example

When **instrumenting** code we want to provide sensible defaults for tags but also we want to allow users to easily change those defaults. A `TagsProvider` interface is a description of what tags we should create for an `Observation.Context`. See the full usage example of an instrumentation together with overriding the default tags.

```java
public class TagsProviderSample {

    public static void main(String[] args) {
        // Registry setup
        ObservationRegistry observationRegistry = new SimpleMeterRegistry()
                // add metrics
                .withTimerObservationHandler();
        observationRegistry
                .observationConfig()
                    // this will be applied to all observations
                    .tagsProvider(new GlobalTagsProvider());

        TaxCalculator taxCalculator = new TaxCalculator(observationRegistry);
        // you can use a setter to override the default tags provider
        taxCalculator.setTagsProvider(new CustomTaxTagsProvider());
        // run the logic you want to observe
        taxCalculator.calculateTax("INCOME_TAX", "1234567890");
    }

}

class TaxContext extends Observation.Context {
    private final String taxType;

    private final String userId;

    TaxContext(String taxType, String userId) {
        this.taxType = taxType;
        this.userId = userId;
    }

    public String getTaxType() {
        return taxType;
    }

    public String getUserId() {
        return userId;
    }
}

// When registered via the `ObservationRegistry#observationConfig#tagsProvider` will be applied globally
class GlobalTagsProvider implements Observation.TagsProvider<Observation.Context> {

    @Override
    public Tags getLowCardinalityTags(Observation.Context context) {
        return Tags.of(Tag.of("cloud.zone", CloudUtils.getZone()));
    }

    @Override
    public Tags getHighCardinalityTags(Observation.Context context) {
        return Tags.of(Tag.of("cloud.instance.id", CloudUtils.getCloudInstanceId()));
    }

    // this will be applicable for all contexts
    @Override
    public boolean supportsContext(Observation.Context context) {
        return true;
    }
}

// Interface for a TagsProvider related to calculating Tax
interface TaxTagsProvider extends Observation.TagsProvider<TaxContext> {
    @Override
    default boolean supportsContext(Observation.Context context) {
        return context instanceof TaxContext;
    }
}

// Default provider of tags related to calculating Tax
class DefaultTaxTagsProvider implements TaxTagsProvider {

    @Override
    public Tags getLowCardinalityTags(TaxContext context) {
        return Tags.of(TaxObservation.TaxLowCardinalityTags.TAX_TYPE.of(context.getTaxType()));
    }

    @Override
    public Tags getHighCardinalityTags(TaxContext context) {
        return Tags.of(TaxObservation.TaxHighCardinalityTags.USER_ID.of(context.getUserId()));
    }
}

/**
 * If micrometer-docs-generator is used, we will automatically
 * generate documentation for your observations.
 * Check this URL https://github.com/micrometer-metrics/micrometer-docs-generator#documentation for setup example and read the DocumentedObservation javadocs.
 */
enum TaxObservation implements DocumentedObservation {
    CALCULATE {
        @Override
        public String getName() {
            return "tax.calculate";
        }

        @Override
        public String getContextualName() {
            return "calculate tax";
        }

        @Override
        public String getPrefix() {
            return "tax";
        }

        @Override
        public TagKey[] getLowCardinalityTagKeys() {
            return TaxLowCardinalityTags.values();
        }

        @Override
        public TagKey[] getHighCardinalityTagKeys() {
            return TaxHighCardinalityTags.values();
        }
    };

    enum TaxLowCardinalityTags implements TagKey {
        TAX_TYPE {
            @Override
            public String getKey() {
                return "tax.type";
            }
        }
    }

    enum TaxHighCardinalityTags implements TagKey {
        USER_ID {
            @Override
            public String getKey() {
                return "tax.user.id";
            }
        }
    }
}

// Class that we want to observe
class TaxCalculator implements Observation.TagsProviderAware<TaxTagsProvider> {

    private final ObservationRegistry observationRegistry;

    private TaxTagsProvider tagsProvider = new DefaultTaxTagsProvider();

    TaxCalculator(ObservationRegistry observationRegistry) {
        this.observationRegistry = observationRegistry;
    }

    public void calculateTax(String taxType, String userId) {
        // Create a new context
        TaxContext taxContext = new TaxContext(taxType, userId);
        // Create a new observation
        Observation observation = TaxObservation.CALCULATE.start(this.observationRegistry, taxContext)
                // Remember to add a tags provider
                .tagsProvider(this.tagsProvider)
                // Example of setting a fixed contextual name
                .contextualName(TaxObservation.CALCULATE.getContextualName());
        // Run the actual logic you want to observe
        observation.scoped(this::calculateInterest);
        // Remember to stop the observation when you're done
        observation.stop();
    }

    private void calculateInterest() {
        // do some work
    }

    // Use this if you want to override the defaults
    @Override
    public void setTagsProvider(TaxTagsProvider tagsProvider) {
        this.tagsProvider = tagsProvider;
    }
}

// Example of user changing the default behaviour
class CustomTaxTagsProvider extends DefaultTaxTagsProvider {
    @Override
    public Tags getLowCardinalityTags(TaxContext context) {
        return super.getLowCardinalityTags(context).and(Tag.of("additional.low.cardinality.tag", "value"));
    }

    @Override
    public Tags getHighCardinalityTags(TaxContext context) {
        return Tags.of("this.would.override.the.default.high.cardinality.tags", "value");
    }
}

class CloudUtils {

    static String getZone() {
        return "...";
    }

    static String getCloudInstanceId() {
        return "...";
    }
}
```


