A popular way to record them is storing the start state in a `Timer.Sample` instance and stop it when the event has ended. In this case, the sample does the recording and reports the data through the `Timer`. +
Recording such measurements could look like this:

[source,java]
----
    ObservationRegistry registry = new SimpleMeterRegistry();
    Observation observation = Observation.start("my.operation", registry);
    try {
		observation.scoped(() -> doSomeWorkHere());
    } finally {
    	observation.stop();
    }
----

One of the new features in Micrometer 2.0 is the ability of registering "handlers" (`ObservationHandler`) that are notified about the lifecycle event of an observation (e.g.: you can run custom code when an observation is stopped/started).
Using this feature lets you add tracing capabilities to your existing metrics instrumentation (see: `DefaultTracingObservationHandler`). The implementation of these handlers does not need to be tracing related, it is completely up to you how you are going to implement them (e.g.: you can add logging capabilities) if you want.

=== Observation.Context

In order to pass information between the instrumented code and the handler (or between handler methods, e.g.: `onStart` and `onStop`), you can utilize a `Observation.Context`. A `Observation.Context` is a `Map`-like container that can store values for you while your handler can access the data inside the context.

=== ObservationHandler Example

Based on this, we can implement a simple handler that lets the users know about its invocations by printing them out to `stdout`.

[source,java]
----
class SimpleHandler implements ObservationHandler<Observation.Context> {
    @Override
    public void onStart(Observation.Context context) {
        System.out.println("START " + "data: " + context.get(String.class));
    }

    @Override
    public void onError(Observation.Context context) {
        System.out.println("ERROR " + "data: " + context.get(String.class) + ", error: " + context.getError().get());
    }

    @Override
    public void onStop(Observation.Context context) {
        System.out.println("STOP  " + "data: " + context.get(String.class));
    }

    @Override
    public boolean supportsContext(Timer.HandlerContext handlerContext) {
        return true; // you can decide if your handler should be invoked for this context object or not
    }
}
----

You can register this handler like this:

[source,java]
----
ObservationRegistry registry = new SimpleMeterRegistry();
registry.observationConfig().observationHandler(new SimpleHandler());
----

And instrument your codebase. Using the `scoped` method example:

[source,java]
----
// using a context is optional, you can call start without it: Observation.start(name, registry)
ObservationRegistry registry = new SimpleMeterRegistry();
Observation.Context context = new Observation.Context().put(String.class, "test");
Observation observation = Observation.start("my.operation", context, registry);
try {
    observation.scoped(() -> doSomeWorkHere());
} finally {
    observation.stop();
}
----

Fully taking control of the scoping mechanism.

[source,java]
----
// using a context is optional, you can call start without it: Observation.start(name, registry)
ObservationRegistry registry = new SimpleMeterRegistry();
Observation.Context context = new Observation.Context().put(String.class, "test");
Observation observation = Observation.start("my.operation", context, registry);
try (Observation.Scope scope = observation.openScope()) {
  doSomeWorkHere();
} observation(Exception ex) {
  sample.error(ex); // and don't forget to handle exceptions
  throw ex;
} finally {
  observation.stop();
}
----

