Micrometer Tracing comes with `micrometer-tracing-test` and `micrometer-tracing-integration-test` modules.

For unit tests it provides a `SimpleTracer` that is a test implementation of a `Tracer`.

For the integration tests it provides a `SampleTestRunner` mechanism that you can hook into your samples.
It will

* Configure a OpenZipkin Brave Tracer
** Set it up with Tanzu Observability by Wavefront Reporter
** Set it up with OpenZipkin Zipkin Reporter
* Configure a OpenTelemetry Tracer
** Set it up with Tanzu Observability by Wavefront Exporter
** Set it up with OpenZipkin Zipkin Exporter
* Run all the combinations above against the user code and running infrastructure

== Installing

The following example shows the required dependency in Gradle (assuming that Micrometer Tracing BOM has been added):

[source,groovy,subs=+attributes]
----
testImplementation 'io.micrometer:micrometer-tracing-test' // for unit tests
testImplementation 'io.micrometer:micrometer-tracing-integration-test' // for integration tests
----

The following example shows the required dependency in Maven (assuming that Micrometer Tracing BOM has been added):

[source,xml,subs=+attributes]
----
<dependency>
  <groupId>io.micrometer</groupId>
  <artifactId>micrometer-tracing-test</artifactId> <!-- For unit tests -->
  <scope>test</scope>
</dependency>
<dependency>
  <groupId>io.micrometer</groupId>
  <artifactId>micrometer-tracing-integration-test</artifactId> <!-- For integration tests -->
  <scope>test</scope>
</dependency>
----

== Running unit tests

To run unit tests of your custom handler you may want to use the `SimpleTracer` test `Tracer` implementation. Let's assume the following custom `TracingRecordingHandler`.

[source,java,subs=+attributes]
-----
public class MyTracingRecordingHandler implements TracingRecordingHandler<MyCustomHandlerContext> {

	private final Tracer tracer;

	public MyTracingRecordingHandler(Tracer tracer) {
		this.tracer = tracer;
	}

	@Override public Tracer getTracer() {
		return this.tracer;
	}

	@Override public void onStart(Timer.Sample sample, MyCustomHandlerContext context) {
		String databaseName = context.getDatabaseName();
		Span.Builder builder = this.tracer.spanBuilder().kind(Span.Kind.CLIENT)
				.remoteServiceName(databaseName);
		getTracingContext(context).setSpan(builder.start());
	}

	@Override public void onError(Timer.Sample sample, MyCustomHandlerContext context, Throwable throwable) {
		getTracingContext(context).getSpan().error(throwable);
	}

	@Override public void onStop(Timer.Sample sample, MyCustomHandlerContext context, Timer timer, Duration duration) {
		TracingContext tracingContext = getTracingContext(context);
		Span span = tracingContext.getSpan();
		span.name(context.getContextualName());
		tagSpan(context, timer.getId(), span);
		span.end();
	}

	@Override public boolean supportsContext(Timer.HandlerContext context) {
		return context instanceof MyCustomHandlerContext;
	}
}
-----

To verify whether the spans got properly created we can use the `SimpleTracer` as follows:

[source,java,subs=+attributes]
-----
class SomeComponentThatIsUsingMyTracingRecordingHandlerTests {

	ObservationRegistry registry = new SimpleMeterRegistry();
	
	SomeComponent someComponent = new SomeComponent(registry);

	SimpleTracer simpleTracer = new SimpleTracer();

	MyTracingRecordingHandler handler = new MyTracingRecordingHandler(simpleTracer);

	@BeforeEach
	void setup() {
		registry.config().observationHandler(handler);
	}

	@Test 
	void should_store_a_span() {
		someComponent.doSthThatShouldCreateSpans(); // this code will call actual Observation API

		TracerAssert.assertThat(simpleTracer)
				.onlySpan()
					.hasNameEqualTo("insert user")
					.hasSpanWithKindEqualTo(Span.Kind.CLIENT)
					.hasRemoteServiceNameEqualTo("mongodb-database")
					.hasTag("mongodb.command", "insert")
					.hasTag("mongodb.collection", "user")
					.hasTagWithKey("mongodb.cluster_id")
					.assertThatThrowable()
						.isInstanceOf(IllegalAccessException.class)
						.backToSpan()
					.hasIpThatIsBlank()
					.hasPortThatIsNotSet();
	}

}
-----

== Running integration tests

The following example shows how you can run your code to test against running Tanzu Observability by Wavefront instance and Zipkin.

[source,java,subs=+attributes]
-----
class TestTest extends SampleTestRunner {

	TestTest() {
		super(SamplerRunnerConfig
				.builder()
				.wavefrontApplicationName("my-app")
				.wavefrontServiceName("my-service")
				.wavefrontToken("...")
				.wavefrontUrl("...")
				.zipkinUrl("...") // defaults to localhost:9411
				.build());
	}
	
	// Here you can add your own custom handlers in the desired order
	@Override
	public BiConsumer<BuildingBlocks, Deque<ObservationHandler>> customizeObservationHandlers() {
		return (bb, ObservationHandlers) -> {
			ObservationHandlers.add(ObservationHandlers.size() - 1, new ReactorNettyTracingRecordingHandler(bb.getTracer()));
			ObservationHandlers.addFirst(new ReactorNettyHttpClientTracingRecordingHandler(bb.getTracer(), bb.getHttpClientHandler()));
			ObservationHandlers.addFirst(new ReactorNettyHttpServerTracingRecordingHandler(bb.getTracer(), bb.getHttpServerHandler()));
		};
	}

	// Here you can pass the code you want to run the instrumentation against
	@Override
	public BiConsumer<Tracer, MeterRegistry> yourCode() {
		// example for testing Reactor Netty
		byte[] bytes = new byte[1024*8];
		Random rndm = new Random();
		rndm.nextBytes(bytes);
		return (tracer, meterRegistry) ->
				HttpClient.create()
						.wiretap(true)
						.metrics(true, Function.identity())
						.post()
						.uri("https://httpbin.org/post")
						.send(ByteBufMono.fromString(Mono.just(new String(bytes))))
						.responseContent()
						.aggregate()
						.block();
	}
}
-----
